### ISSUE TITLE
highlighting doesn't appear

### ISSUE THREAD

**Issue by rdrr1990** [louabill/ado-mode#1]
Howdy,

Looks very useful! Brand new to `emacs`, so sure I'm missing something... I have everything in `~\.emacs.d`. From that directory in `Terminal`
```
cat default.el
	(add-to-list 'load-path "~/.emacs.d/ado-mode/lisp")
	(require 'ado-mode)
```
and 
```
ls 
ado-mode	auto-save-list	default.el
```
and
```
ls ado-mode
INSTALL.md			changes.txt			lisp				setup_aids
README.md			docs4github			readme.txt			syntax_testers
changes.md			font_highlighting_example.ado	scripts				templates
```
Any idea why after re-starting `emacs` and opening `.do` file, the code would still appear in black and white? Many thanks!

**Comment by louabill** [comment]
You would need to tell Emacs to associate do-files with `ado-mode`. Either that, or just start ado-mode via `M-x ado-mode`. After the first load of `ado-mode` in an Emacs session, it'll then look for the extensions. Sorry fo the massively late reply.
