### ISSUE TITLE
Sending a command changes focus to stata window

### ISSUE THREAD

**Issue by nimafazeli** [louabill/ado-mode#11]
I could not find any setting to control this behavior and not sure whether this is an issue with the package. I am on Windows 10.

Here is the issue: 

When running a command from emacs, i.e. M-RET while on a line, the command gets correctly sent to Stata. 
Here is the bad behaviour: the focus changes to Stata, i.e. the Stata window becomes the active window as well which I think is undesirable. 

It is more desirable that emacs window remains active.  If I am doing the editing on emacs, I am not doing any editing on Stata and just view the results from there.

**Comment by louabill** [comment]
Changing focus to Stata is the default behavior. You can change this to leave the focus in the Emacs window two ways:

To change for a particular buffer, click on the menu item
  `Ado-mode > Options > Return to Emacs after submission`
To change for all future sessions, try `M-x customize-group<RET>ado<RET>`, then click on the `Stata interaction` link, then toggle the `Ado comeback flag`, then click on the `Apply and Save` button.

Coming back to Emacs works in Windows and on the Mac, but does not work in *nix.
