### ISSUE TITLE
Ado Comeback Flag not working

### ISSUE THREAD

**Issue by chenwilliam77** [louabill/ado-mode#13]
When I toggle the Ado Comeback Flag to non-nil and run a command, instead of going back to the original buffer, a new buffer gets opened. I'm working on a Mac FYI. I also double checked that when going to Ado Mode and going to Options, I see that "Return to Emacs after submission" has been checked.

**Comment by louabill** [comment]
Sorry for the tremendouslly late reply.

I'm not seeing the bad behavior on my machine, so I'll need a little more info to see if I can reproduce the behavior. 

Could you please give more details (Emacs version, macOS version, Stata version)?

Thanks.

(FWIW, I'm using Aquamacs 3.6-beta  GNU Emacs 25.3.50.1), macOS 11.6, Stata 17.)
