### ISSUE TITLE
StataNow breaks ado-mode

### ISSUE THREAD

**Issue by hlcny** [louabill/ado-mode#15]
Hi,
I'm a long-time user of ado-mode, from Stata 15 to 18--it's excellent! Thanks so much. Unfortunately, I got updated to StataNow today and the upgrade breaks send2stata. It gives the "Oops No Stata Running" error box. I was able to verify this is the cause by reverting my executable to the "_old' version that the upgrade automatically saves and it works fine again. I believe this is a probably a simple fix to the Autoit script to look for the new product name.

I'm on Win 11

I hope you can fix this soon.

Best regards

**Comment by louabill** [comment]
I'll take a look in the upcoming weeks. My life is a bit on its head right now, so updates are slow.

**Comment by hlcny** [comment]
Thank you. In the interim I figure out how to fix it myself…as I expected a super simple tweak to the send2stata code, just add StataNow to the regex:

$theStatas = WinList("[REGEXPTITLE:(Stata/(BE/IC|SE|MP))|(Small Stata)|(StataNow/(BE/IC|SE|MP))]")

 

Then recompiled it and swapped my new send2stata with the old one and it works.

**Comment by louabill** [comment]
I added a (simpler) fix and will push it up likely tomorrow (since I need to keep the manual downloads and all that stuff coordinated).

**Comment by louabill** [comment]
Oh, and I should check to add any new Stata commands in StataNow. I know of one (-xtvar-), but need to check the whatsnew to see if there are others.

What's odd is that this 18.0 vs 18.5 will make me need to change the way that I number my ado-mode versions, as they have been 1.Stataversion.Statasubversion.adomode-version, but now ther are 2 different current Stata version 18s.
