### ISSUE TITLE
Send code to Stata in terminal

### ISSUE THREAD

**Issue by jarathomas** [louabill/ado-mode#6]
Many thanks for ado-mode!  I can send code to the Stata GUI, but am wondering if it is possible to send code
to Stata running in a terminal.  More specifically, I would like to have two Emacs buffers open, one with code and
another with a Stata session that executes the sent code.

**Comment by louabill** [comment]
I'm 99% sure that I cannot send code to a terminal, but it likely depends on the operating system. What OS are you using? Also: is the reason for the terminal because you need to work on a remote machine?

**Comment by jarathomas** [comment]
Thanks for the response.  I'm on Ubuntu (but also use Mac OS) with my local machine (not a remote server).  I just find it convenient to have everything in a single window w/ 2 buffers (code and Stata output).  I remember ESS's old stata mode doing 
this so I thought/hoped it would be a simple tweak.  Sounds like a a pain though, so no worries.  

Thanks again for ado-mode!  Using it right now :)

**Comment by louabill** [comment]
Ah, so you'd like to have an Emacs buffer running Stata and and Emacs buffer with code in `ado-mode`. That might be easier than sending to an arbitrary Terminal window. I'm not going to be able to reproduce the complexity of `ESS-mode`, but maybe I can hack together something passable. No promises, but at least it sounds like something interesting to pursue.

**Comment by ikegami4** [comment]
Thank you for ado-mode! Although jarathomas has already closed this issue, I just want to say that I also wish if ado-mode could send stata command form an emacs buffer to another emacs buffer (I guess ESS used to call inferior stata buffer). This .el allows one to send stata comand from do file buffer to stata terminal buffer http://faculty.washington.edu/tlumley/stata.el
I guess ESS used to use and revise this. What I know is that this one cannot open a widow for stata graphic like stata GUI and so I need to save a graphic file and open it with another buffer. Some people may prefer current ado-mode with stata GUI becuase of this. Maybe one can choose where to send a stata command.

Another wish I have and I am not sure whether I should write here or another issue is as follows:
Current version of ado-mode (1.7) sends a stata command to stata GUI and the when one goes gack to emacs, the slected buffer is async shell buffer ando so one has to move from the buffer to the original stata buffer to keep editing it. This is another extra step I can wish to avoid.

Thank you in advance for your consideration. Please let me know if I can clarify more.
